"""initial

Revision ID: 978b8fc1ebc3
Revises: f52c7af886b2
Create Date: 2026-02-27 08:04:04.597382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '978b8fc1ebc3'
down_revision: Union[str, None] = 'f52c7af886b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS postgis')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'VOLUNTEER', 'NGO', 'ADMIN', 'OFFICIAL', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_created_at'), 'emergency_contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_id'), 'emergency_contacts', ['id'], unique=False)
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.create_table('guidelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('phase', sa.Enum('BEFORE', 'DURING', 'AFTER', name='guideline_phase'), nullable=False),
    sa.Column('hazard_type', sa.Enum('FLOOD', 'CYCLONE', 'EARTHQUAKE', 'HEATWAVE', 'LANDSLIDE', 'GENERIC', name='hazard_type'), nullable=False),
    sa.Column('region', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_guidelines_region ON guidelines USING gist (region)')
    op.create_index(op.f('ix_guidelines_created_at'), 'guidelines', ['created_at'], unique=False)
    op.create_index(op.f('ix_guidelines_hazard_type'), 'guidelines', ['hazard_type'], unique=False)
    op.create_index(op.f('ix_guidelines_id'), 'guidelines', ['id'], unique=False)
    op.create_index(op.f('ix_guidelines_language_code'), 'guidelines', ['language_code'], unique=False)
    op.create_index(op.f('ix_guidelines_phase'), 'guidelines', ['phase'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incident_severity'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'VERIFIED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='incident_status'), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('media_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute('CREATE INDEX IF NOT EXISTS idx_incidents_location ON incidents USING gist (location)')
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_location'), 'incidents', ['location'], unique=False)
    op.create_index(op.f('ix_incidents_reporter_id'), 'incidents', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('incident_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('predicted_severity', sa.String(length=50), nullable=False),
    sa.Column('estimated_resources_required', sa.Integer(), nullable=True),
    sa.Column('estimated_budget', sa.Float(), nullable=True),
    sa.Column('forecast_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prediction_horizon_days', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('ml_pipeline_id', sa.String(length=100), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence_level >= 0.0 AND confidence_level <= 1.0', name='check_confidence_range'),
    sa.CheckConstraint('risk_score >= 1 AND risk_score <= 10', name='check_risk_score_range'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_predictions_created_at'), 'incident_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_predictions_forecast_date'), 'incident_predictions', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_incident_predictions_id'), 'incident_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_incident_predictions_incident_id'), 'incident_predictions', ['incident_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('risk_type', sa.Enum('FLOOD', 'CYCLONE', 'EARTHQUAKE', 'LANDSLIDE', 'WILDFIRE', name='risk_type', native_enum=False), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('features_used', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_incident_id'), 'predictions', ['incident_id'], unique=False)
    op.create_index(op.f('ix_predictions_risk_type'), 'predictions', ['risk_type'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='task_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='task_priority'), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_incident_id'), 'tasks', ['incident_id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_incident_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_predictions_risk_type'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_incident_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_incident_predictions_incident_id'), table_name='incident_predictions')
    op.drop_index(op.f('ix_incident_predictions_id'), table_name='incident_predictions')
    op.drop_index(op.f('ix_incident_predictions_forecast_date'), table_name='incident_predictions')
    op.drop_index(op.f('ix_incident_predictions_created_at'), table_name='incident_predictions')
    op.drop_table('incident_predictions')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_reporter_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_location'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index('idx_incidents_location', table_name='incidents', postgresql_using='gist')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_guidelines_phase'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_language_code'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_id'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_hazard_type'), table_name='guidelines')
    op.drop_index(op.f('ix_guidelines_created_at'), table_name='guidelines')
    op.drop_index('idx_guidelines_region', table_name='guidelines', postgresql_using='gist')
    op.drop_table('guidelines')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_id'), table_name='emergency_contacts')
    op.drop_index(op.f('ix_emergency_contacts_created_at'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
